services:

  nats-server:
    image: nats:latest


  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=5004
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=5001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  # orders-ms:
  #   depends_on:
  #     - orders-db
  #   build: ./orders-ms
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=5002
  #     - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
  #     - NATS_SERVERS=${NATS_SERVERS}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SERVER_URL=${SERVER_URL}